package com.hkafeidou.springcloudproviderdept.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import com.hkafeidou.springcloudsimple.infrastructure.entity.Department;

@Repository
@Mapper
public interface DepartmentMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSM_Department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSM_Department
     *
     * @mbg.generated
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSM_Department
     *
     * @mbg.generated
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSM_Department
     *
     * @mbg.generated
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSM_Department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Department record);
}
